(() => {
  'use strict';

  const C=window.ParlayTrackerCore;
  const SCHEDULE='https://statsapi.mlb.com/api/v1/schedule';
  const FEED='https://statsapi.mlb.com/api/v1.1/game';
  const ESPN='https://site.api.espn.com/apis/site/v2/sports';
  const cache=new Map();
  const clean=value=>String(value??'').trim();
  const norm=value=>clean(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
  const validTime=value=>{const date=new Date(value||'');return Number.isNaN(date.getTime())?'':date.toISOString();};
  const dashDate=value=>{const text=clean(value).replace(/\D/g,'').slice(0,8);return text.length===8?`${text.slice(0,4)}-${text.slice(4,6)}-${text.slice(6)}`:'';};
  const gameParts=game=>{const parts=clean(game).split('@').map(value=>value.trim().toUpperCase());return parts.length===2?{away:parts[0],home:parts[1]}:{away:'',home:''};};
  const effectiveLeague=(ticket,leg={})=>clean(leg.league||ticket.league||'MLB').toUpperCase();
  const supportedLeague=league=>['MLB','NBA','WNBA'].includes(clean(league).toUpperCase());
  const MLB_TYPES=new Set(['ml','spread','f5_ml','f5_spread','f5_total_over','f5_total_under','team_total_over','team_total_under','total_over','total_under','pitcher_outs_under','pitcher_ks','pitcher_ks_under','player_hits','player_total_bases','player_runs','player_hr','player_rbi','player_walks','player_stolen_bases','player_hwsb','player_hrrbi','manual','void']);
  const BASKETBALL_TYPES=new Set(['ml','spread','h1_ml','h1_spread','h1_total_over','h1_total_under','team_total_over','team_total_under','total_over','total_under','player_points','player_rebounds','player_assists','player_points_rebounds','player_pr','player_points_assists','player_pa','player_rebounds_assists','player_ra','player_points_rebounds_assists','player_pra','player_double_double','player_triple_double','player_blocks','player_threes','manual','void']);
  const supports=(league,type)=>{const normalizedLeague=clean(league).toUpperCase(),normalizedType=clean(type).toLowerCase();return normalizedLeague==='MLB'?MLB_TYPES.has(normalizedType):normalizedLeague==='NBA'||normalizedLeague==='WNBA'?BASKETBALL_TYPES.has(normalizedType):false;};
  const instanceValue=(ticket,leg,name)=>C.instanceValue?C.instanceValue(ticket,leg,name):(leg?.[name]??ticket?.[name]);
  const startKey=raw=>C.gameStartCT?C.gameStartCT({date:raw,gameDate:raw}):'';
  async function json(url){const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.json();}
  function cacheRequest(key,loader){if(cache.has(key))return cache.get(key);const promise=Promise.resolve().then(loader).catch(error=>{cache.delete(key);throw error;});cache.set(key,promise);return promise;}
  function chooseInstance(candidates,ticket,leg,record,idOf,dateOf){
    if(!candidates.length)return null;const sorted=[...candidates].sort((a,b)=>new Date(dateOf(a)||0)-new Date(dateOf(b)||0));
    const explicitPk=instanceValue(ticket,leg,'gamePk');if(explicitPk!==undefined&&explicitPk!==null&&explicitPk!==''){const value=Number(explicitPk);return Number.isFinite(value)?sorted.find(item=>Number(idOf(item))===value)||null:null;}
    const explicitId=clean(instanceValue(ticket,leg,'gameId'));if(explicitId)return sorted.find(item=>clean(idOf(item))===explicitId)||null;
    const wantedStart=clean(instanceValue(ticket,leg,'gameStart'));if(wantedStart)return sorted.find(item=>startKey(dateOf(item))===wantedStart)||null;
    const rawOrdinal=instanceValue(ticket,leg,'gameNumber');if(rawOrdinal!==undefined&&rawOrdinal!==null&&rawOrdinal!==''){const ordinal=Number(rawOrdinal);return Number.isInteger(ordinal)&&ordinal>=1&&ordinal<=sorted.length?sorted[ordinal-1]:null;}
    if(sorted.length===1)return sorted[0];
    const reference=new Date(instanceValue(ticket,leg,'gameSavedAt')||record.savedAt||record.createdAt||record.updatedAt||'').getTime();
    if(!Number.isFinite(reference))return null;
    return sorted.reduce((best,item)=>{const time=new Date(dateOf(item)||'').getTime();if(!Number.isFinite(time))return best;const distance=Math.abs(time-reference);return !best||distance<best.distance?{item,distance}:best;},null)?.item||null;
  }
  function mlbTeamMatches(team,abbr){return C.teamMatches?C.teamMatches(team||{},abbr):clean(team?.abbreviation).toUpperCase()===clean(abbr).toUpperCase();}
  async function getMlbFeed(record,ticket,leg){
    const date=leg.date||ticket.date,game=leg.game||ticket.game,{away,home}=gameParts(game);if(!date||!away||!home)throw new Error('Invalid MLB event binding');
    const key=['mlb',date,game,record.id,instanceValue(ticket,leg,'gamePk'),instanceValue(ticket,leg,'gameId'),instanceValue(ticket,leg,'gameStart'),instanceValue(ticket,leg,'gameNumber')].join('|');
    return cacheRequest(key,async()=>{const schedule=await json(`${SCHEDULE}?sportId=1&date=${encodeURIComponent(dashDate(date))}&hydrate=team`),candidates=(schedule.dates||[]).flatMap(item=>item.games||[]).filter(item=>mlbTeamMatches(item.teams?.away?.team,away)&&mlbTeamMatches(item.teams?.home?.team,home)),selected=chooseInstance(candidates,ticket,leg,record,item=>item.gamePk,item=>item.gameDate);if(!selected?.gamePk)throw new Error('MLB game instance unavailable');return json(`${FEED}/${selected.gamePk}/feed/live`);});
  }
  const basketballPath=league=>league==='NBA'?'basketball/nba':'basketball/wnba';
  function espnTeamMatches(team,abbr){return C.teamMatches?C.teamMatches(team||{},abbr):clean(team?.abbreviation).toUpperCase()===clean(abbr).toUpperCase();}
  async function getBasketballSummary(record,ticket,leg,league){
    const date=leg.date||ticket.date,game=leg.game||ticket.game,{away,home}=gameParts(game),path=basketballPath(league);if(!date||!away||!home)throw new Error('Invalid basketball event binding');
    const key=[league,date,game,record.id,instanceValue(ticket,leg,'gameId'),instanceValue(ticket,leg,'gameStart'),instanceValue(ticket,leg,'gameNumber')].join('|');
    return cacheRequest(key,async()=>{const board=await json(`${ESPN}/${path}/scoreboard?dates=${encodeURIComponent(clean(date).replace(/\D/g,''))}&limit=100`),candidates=(board.events||[]).filter(event=>{const sides=event?.competitions?.[0]?.competitors||[],awaySide=sides.find(side=>side.homeAway==='away'),homeSide=sides.find(side=>side.homeAway==='home');return espnTeamMatches(awaySide?.team,away)&&espnTeamMatches(homeSide?.team,home);}),selected=chooseInstance(candidates,ticket,leg,record,event=>event.id,event=>event.date);if(!selected?.id)throw new Error('Basketball game instance unavailable');return json(`${ESPN}/${path}/summary?event=${encodeURIComponent(selected.id)}`);});
  }

  const mlbPlays=feed=>feed?.liveData?.plays?.allPlays||[];
  const playTime=play=>validTime(play?.about?.endTime)||validTime(play?.about?.startTime);
  const mlbFinal=feed=>{const status=feed?.gameData?.status||{};return status.abstractGameState==='Final'||/final|game over|completed/i.test(clean(status.detailedState));};
  function latestMlbTime(feed){const list=mlbPlays(feed);for(let index=list.length-1;index>=0;index--){const time=playTime(list[index]);if(time)return time;}return'';}
  const samePerson=(person,name)=>{const personName=norm(person?.fullName||person?.fullNameLastFirst),wanted=norm(name);return Boolean(personName&&wanted&&(personName===wanted||personName.includes(wanted)||wanted.includes(personName)));};
  const totalBases=event=>({single:1,double:2,triple:3,home_run:4})[clean(event).toLowerCase()]||0;
  function threshold(rows,key,target,compare=(value,needed)=>value>=needed){for(const row of rows)if(compare(Number(row[key]||0),Number(target)))return{reached:true,time:row.time||'',row};return{reached:false,time:'',row:rows.at(-1)||null};}
  function playerLedger(feed,name){
    const rows=[];let hits=0,totalBasesValue=0,runs=0,rbi=0,walks=0,homeRuns=0,stolenBases=0;
    for(const play of mlbPlays(feed)){
      const event=clean(play?.result?.eventType).toLowerCase();
      if(samePerson(play?.matchup?.batter,name)){const bases=totalBases(event);if(bases){hits++;totalBasesValue+=bases;if(event==='home_run')homeRuns++;}if(event==='walk'||event==='intent_walk')walks++;rbi+=Number(play?.result?.rbi||0);}
      for(const runner of play?.runners||[]){if(!samePerson(runner?.details?.runner,name))continue;if(clean(runner?.movement?.end).toLowerCase()==='score'&&!runner?.movement?.isOut)runs++;const type=clean(runner?.details?.eventType||runner?.details?.event).toLowerCase();if(type.includes('stolen_base'))stolenBases++;}
      rows.push({time:playTime(play),hits,totalBases:totalBasesValue,runs,rbi,walks,homeRuns,stolenBases,hrrbi:hits+runs+rbi,hwsb:hits+walks+stolenBases});
    }
    return rows;
  }
  function findMlbPlayer(feed,name){const wanted=norm(name),teams=feed?.liveData?.boxscore?.teams||{},players=['away','home'].flatMap(side=>Object.values(teams[side]?.players||{}));const exact=players.filter(player=>norm(player?.person?.fullName)===wanted);if(exact.length===1)return exact[0];if(exact.length>1)return null;const partial=players.filter(player=>{const value=norm(player?.person?.fullName);return value&&(value.includes(wanted)||wanted.includes(value));});return partial.length===1?partial[0]:null;}
  function parseIPToOuts(raw){const match=String(raw??'').trim().match(/^(\d+)(?:\.(\d))?$/);if(!match)return null;const innings=Number(match[1]),fraction=Number(match[2]||0);return Number.isInteger(innings)&&[0,1,2].includes(fraction)?innings*3+fraction:null;}
  function mlbFinalPlayerValue(feed,type,name){const player=findMlbPlayer(feed,name),batting=player?.stats?.batting||{},pitching=player?.stats?.pitching||{};switch(type){case'player_hits':return Number(batting.hits);case'player_total_bases':return batting.totalBases!=null?Number(batting.totalBases):null;case'player_runs':return Number(batting.runs);case'player_hr':return Number(batting.homeRuns);case'player_rbi':return Number(batting.rbi??batting.runsBattedIn);case'player_walks':return Number(batting.baseOnBalls??batting.walks);case'player_stolen_bases':return Number(batting.stolenBases);case'player_hrrbi':{const values=[batting.hits,batting.runs,batting.rbi??batting.runsBattedIn].map(Number);return values.every(Number.isFinite)?values.reduce((a,b)=>a+b,0):null;}case'player_hwsb':{const values=[batting.hits,batting.baseOnBalls??batting.walks,batting.stolenBases].map(Number);return values.every(Number.isFinite)?values.reduce((a,b)=>a+b,0):null;}case'pitcher_ks':case'pitcher_ks_under':return Number(pitching.strikeOuts??pitching.strikeouts??pitching.so);case'pitcher_outs_under':return pitching.outs!=null?Number(pitching.outs):parseIPToOuts(pitching.inningsPitched);default:return null;}}
  function pitcherExitTime(feed,name,lastIndex){const list=mlbPlays(feed);if(lastIndex<0)return'';for(let index=lastIndex+1;index<list.length;index++)if(!samePerson(list[index]?.matchup?.pitcher,name))return validTime(list[index]?.about?.startTime)||playTime(list[index]);const player=findMlbPlayer(feed,name);return player?.gameStatus?.isCurrentPitcher===false?playTime(list[lastIndex]):'';}
  function pitcherLedger(feed,name){const rows=[];let strikeouts=0,outs=0,lastIndex=-1;const list=mlbPlays(feed);for(let index=0;index<list.length;index++){const play=list[index];if(samePerson(play?.matchup?.pitcher,name)){lastIndex=index;if(clean(play?.result?.eventType).toLowerCase()==='strikeout')strikeouts++;const start=Number(play?.about?.startOuts||0),end=Number(play?.count?.outs||0),delta=end-start;if(Number.isFinite(delta)&&delta>0)outs+=delta;}rows.push({time:playTime(play),strikeouts,outs});}return{rows,exitTime:pitcherExitTime(feed,name,lastIndex)};}
  function mlbTeamScore(play,feed,team){const away=clean(feed?.gameData?.teams?.away?.abbreviation).toUpperCase(),home=clean(feed?.gameData?.teams?.home?.abbreviation).toUpperCase(),selected=clean(team).toUpperCase();if(selected===away)return Number(play?.result?.awayScore);if(selected===home)return Number(play?.result?.homeScore);return null;}
  function scoreThreshold(feed,leg,over){const target=Number(leg.target),teamMarket=clean(leg.type).startsWith('team_total');for(const play of mlbPlays(feed)){const away=Number(play?.result?.awayScore),home=Number(play?.result?.homeScore);if(!Number.isFinite(away)||!Number.isFinite(home))continue;const current=teamMarket?mlbTeamScore(play,feed,leg.team):away+home;if(current==null)continue;if(over?current>target:current>target)return{reached:true,time:playTime(play),value:current};}return{reached:false,time:'',value:null};}
  function mlbFinalScores(feed,team){const line=feed?.liveData?.linescore?.teams||{},away=clean(feed?.gameData?.teams?.away?.abbreviation).toUpperCase(),home=clean(feed?.gameData?.teams?.home?.abbreviation).toUpperCase(),selected=clean(team).toUpperCase();if(selected!==away&&selected!==home)return null;const mine=selected===away?Number(line.away?.runs):Number(line.home?.runs),opponent=selected===away?Number(line.home?.runs):Number(line.away?.runs);return Number.isFinite(mine)&&Number.isFinite(opponent)?{mine,opp:opponent}:null;}
  function mlbFinalTotal(feed){const line=feed?.liveData?.linescore?.teams||{},away=Number(line.away?.runs),home=Number(line.home?.runs);return Number.isFinite(away)&&Number.isFinite(home)?away+home:null;}
  function f5Snapshot(feed){const plays=mlbPlays(feed),fifth=plays.filter(play=>Number(play?.about?.inning)===5),later=plays.some(play=>Number(play?.about?.inning)>5),current=Number(feed?.liveData?.linescore?.currentInning||0),complete=Boolean(fifth.length&&(later||current>5||mlbFinal(feed)));if(!complete)return{complete:false,time:'',away:null,home:null};const innings=feed?.liveData?.linescore?.innings||[];let away=0,home=0;for(const inning of innings)if(Number(inning.num)<=5){away+=Number(inning.away?.runs||0);home+=Number(inning.home?.runs||0);}let time='';for(let index=fifth.length-1;index>=0;index--){time=playTime(fifth[index]);if(time)break;}return{complete:true,time,away,home};}
  function finalLineStatus(value,target,direction){if(value===target)return'VOID';return direction==='over'?(value>target?'WIN':'LOSS'):(value<target?'WIN':'LOSS');}
  function settleMlbLeg(leg,feed){
    const type=clean(leg.type),target=Number(leg.target),final=mlbFinal(feed),end=final?latestMlbTime(feed):'';
    if(type==='void')return{status:'VOID',settledAt:end,reason:'Void finalized'};
    if(type==='manual')return{status:'PENDING',settledAt:'',reason:'Manual'};
    const playerKey={player_hits:'hits',player_total_bases:'totalBases',player_runs:'runs',player_hr:'homeRuns',player_rbi:'rbi',player_walks:'walks',player_stolen_bases:'stolenBases',player_hrrbi:'hrrbi',player_hwsb:'hwsb'}[type];
    if(playerKey){const reached=threshold(playerLedger(feed,leg.player),playerKey,target);if(reached.reached)return{status:'WIN',settledAt:reached.time,reason:`${playerKey} target reached`};if(final){const value=mlbFinalPlayerValue(feed,type,leg.player);if(value==null||!Number.isFinite(value))return{status:'UNAVAILABLE',settledAt:'',reason:'Final player statistic unavailable'};return{status:value>=target?'WIN':'LOSS',settledAt:end,reason:value>=target?'Target confirmed by final box score':'Game final below target'};}return{status:'LIVE',settledAt:'',reason:''};}
    if(type==='pitcher_ks'){const ledger=pitcherLedger(feed,leg.player),reached=threshold(ledger.rows,'strikeouts',target);if(reached.reached)return{status:'WIN',settledAt:reached.time,reason:'Strikeout target reached'};const finalValue=mlbFinalPlayerValue(feed,type,leg.player);if(finalValue!=null&&Number.isFinite(finalValue)&&finalValue>=target)return{status:'WIN',settledAt:'',reason:'Target confirmed by final box score'};if(ledger.exitTime)return{status:'LOSS',settledAt:ledger.exitTime,reason:'Pitcher removed below target'};if(final)return finalValue==null||!Number.isFinite(finalValue)?{status:'UNAVAILABLE',settledAt:'',reason:'Final pitcher statistic unavailable'}:{status:'LOSS',settledAt:end,reason:'Game final below target'};return{status:'LIVE',settledAt:'',reason:''};}
    if(type==='pitcher_ks_under'||type==='pitcher_outs_under'){const ledger=pitcherLedger(feed,leg.player),key=type==='pitcher_ks_under'?'strikeouts':'outs',loss=threshold(ledger.rows,key,target,(value,needed)=>value>needed),boxValue=mlbFinalPlayerValue(feed,type,leg.player),last=boxValue!=null&&Number.isFinite(boxValue)?boxValue:Number(ledger.rows.at(-1)?.[key]||0);if(loss.reached)return{status:'LOSS',settledAt:loss.time,reason:`${key} under exceeded`};if(last>target)return{status:'LOSS',settledAt:'',reason:'Under exceeded in box score'};if(ledger.exitTime||final){if(boxValue==null&&!ledger.rows.length)return{status:'UNAVAILABLE',settledAt:'',reason:'Final pitcher statistic unavailable'};const status=last===target?'VOID':'WIN';return{status,settledAt:ledger.exitTime||end,reason:status==='VOID'?'Pitcher finished on line':'Pitcher removed under target'};}return{status:'LIVE',settledAt:'',reason:''};}
    if(['team_total_over','total_over'].includes(type)){const reached=scoreThreshold(feed,leg,true);if(reached.reached)return{status:'WIN',settledAt:reached.time,reason:'Over threshold crossed'};if(final){const scores=type==='team_total_over'?mlbFinalScores(feed,leg.team):null,value=type==='team_total_over'?scores?.mine:mlbFinalTotal(feed);if(value==null)return{status:'UNAVAILABLE',settledAt:'',reason:'Final score unavailable'};return{status:finalLineStatus(value,target,'over'),settledAt:end,reason:'Game final'};}return{status:'LIVE',settledAt:'',reason:''};}
    if(['team_total_under','total_under'].includes(type)){const loss=scoreThreshold(feed,leg,false);if(loss.reached)return{status:'LOSS',settledAt:loss.time,reason:'Under threshold crossed'};if(final){const scores=type==='team_total_under'?mlbFinalScores(feed,leg.team):null,value=type==='team_total_under'?scores?.mine:mlbFinalTotal(feed);if(value==null)return{status:'UNAVAILABLE',settledAt:'',reason:'Final score unavailable'};return{status:finalLineStatus(value,target,'under'),settledAt:end,reason:'Game final'};}return{status:'LIVE',settledAt:'',reason:''};}
    if(['ml','spread'].includes(type)){if(!final)return{status:'LIVE',settledAt:'',reason:''};const scores=mlbFinalScores(feed,leg.team);if(!scores)return{status:'UNAVAILABLE',settledAt:'',reason:'Final score unavailable'};const adjusted=type==='spread'?scores.mine+target:scores.mine;return{status:adjusted>scores.opp?'WIN':adjusted<scores.opp?'LOSS':'VOID',settledAt:end,reason:'Game final'};}
    if(['f5_ml','f5_spread','f5_total_over','f5_total_under'].includes(type)){const half=f5Snapshot(feed);if(!half.complete)return{status:'LIVE',settledAt:'',reason:''};if(type.startsWith('f5_total')){const value=half.away+half.home,direction=type.endsWith('_over')?'over':'under';return{status:finalLineStatus(value,target,direction),settledAt:half.time,reason:'First five complete'};}const awayCode=clean(feed?.gameData?.teams?.away?.abbreviation).toUpperCase(),homeCode=clean(feed?.gameData?.teams?.home?.abbreviation).toUpperCase(),selected=clean(leg.team).toUpperCase();if(selected!==awayCode&&selected!==homeCode)return{status:'UNAVAILABLE',settledAt:'',reason:'Team unavailable'};const mine=selected===awayCode?half.away:half.home,opponent=selected===awayCode?half.home:half.away,adjusted=type==='f5_spread'?mine+target:mine;return{status:adjusted>opponent?'WIN':adjusted<opponent?'LOSS':'VOID',settledAt:half.time,reason:'First five complete'};}
    return{status:final?'UNAVAILABLE':'LIVE',settledAt:'',reason:'Unsupported MLB settlement mapping'};
  }

  const basketballPlays=summary=>summary?.plays||[];
  const basketballTime=play=>validTime(play?.wallclock);
  const basketballFinal=summary=>Boolean(summary?.header?.competitions?.[0]?.status?.type?.completed);
  function basketballFinalTime(summary){if(!basketballFinal(summary))return'';const list=basketballPlays(summary);for(let index=list.length-1;index>=0;index--){const time=basketballTime(list[index]);if(time)return time;}return'';}
  function basketballCompetitors(summary){const competitors=summary?.header?.competitions?.[0]?.competitors||[];return{away:competitors.find(side=>side.homeAway==='away')||{},home:competitors.find(side=>side.homeAway==='home')||{}};}
  function basketballSides(summary){const competitors=basketballCompetitors(summary);return{away:competitors.away.team||{},home:competitors.home.team||{}};}
  function basketballSide(summary,team){const sides=basketballSides(summary);if(espnTeamMatches(sides.away,team))return'away';if(espnTeamMatches(sides.home,team))return'home';return'';}
  function basketballScore(play,summary,team){const side=basketballSide(summary,team);if(!side)return null;const value=Number(side==='away'?play?.awayScore:play?.homeScore);return Number.isFinite(value)?value:null;}
  function basketballOpponent(play,summary,team){const side=basketballSide(summary,team);if(!side)return null;const value=Number(side==='away'?play?.homeScore:play?.awayScore);return Number.isFinite(value)?value:null;}
  function basketballPlayerStats(summary,team,name){const containers=(summary?.boxscore?.players||[]).filter(container=>espnTeamMatches(container.team||{},team)),wanted=norm(name),rows=containers.flatMap(container=>(container.statistics||[]).flatMap(group=>(group.athletes||[]).map(row=>({row,group,name:norm(row?.athlete?.displayName||row?.athlete?.fullName||row?.displayName||row?.name)}))));const names=[...new Set(rows.map(item=>item.name).filter(Boolean))],exact=names.filter(value=>value===wanted),partial=names.filter(value=>value.includes(wanted)||wanted.includes(value)),selected=exact.length===1?exact[0]:exact.length?'' :partial.length===1?partial[0]:'';if(!selected)return null;const stats={};for(const item of rows){if(item.name!==selected)continue;const values=item.row.stats||[];(item.group.labels||[]).forEach((key,index)=>stats[key]=values[index]);(item.group.names||[]).forEach((key,index)=>stats[key]=values[index]);}return stats;}
  function basketballStat(stats,keys){if(!stats)return null;for(const key of keys){if(stats[key]==null)continue;const raw=String(stats[key]);if(raw.includes('-'))continue;const value=Number(raw);if(Number.isFinite(value))return value;}return null;}
  function basketballFinalPlayerValue(summary,leg,key){const stats=basketballPlayerStats(summary,leg.team,leg.player);if(!stats)return null;const values={points:basketballStat(stats,['PTS','points','Points']),rebounds:basketballStat(stats,['REB','rebounds','Rebounds']),assists:basketballStat(stats,['AST','assists','Assists']),threes:basketballStat(stats,['3PM','3PTM','FG3M']),blocks:basketballStat(stats,['BLK','blocks','Blocks']),steals:basketballStat(stats,['STL','steals','Steals'])};if(key==='pr')return values.points!=null&&values.rebounds!=null?values.points+values.rebounds:null;if(key==='pa')return values.points!=null&&values.assists!=null?values.points+values.assists:null;if(key==='ra')return values.rebounds!=null&&values.assists!=null?values.rebounds+values.assists:null;if(key==='pra')return values.points!=null&&values.rebounds!=null&&values.assists!=null?values.points+values.rebounds+values.assists:null;if(key==='doubleCount'){const list=[values.points,values.rebounds,values.assists,values.blocks,values.steals];return list.every(value=>value!=null)?list.filter(value=>value>=10).length:null;}return values[key]??null;}
  function basketballPlayerLedger(summary,name){const wanted=norm(name),rows=[];let points=0,rebounds=0,assists=0,threes=0,blocks=0,steals=0;for(const play of basketballPlays(summary)){const text=clean(play?.text),normalized=norm(text),mentions=Boolean(wanted&&normalized.includes(wanted)),primary=Boolean(wanted&&normalized.startsWith(wanted));if(primary&&play?.scoringPlay){points+=Number(play?.scoreValue||0);if(Number(play?.scoreValue)===3)threes++;}if(mentions&&/rebound/i.test(text))rebounds++;if(mentions&&/assist/i.test(text))assists++;if(mentions&&/block/i.test(text))blocks++;if(mentions&&/steal/i.test(text))steals++;rows.push({time:basketballTime(play),points,rebounds,assists,threes,blocks,steals,pr:points+rebounds,pa:points+assists,ra:rebounds+assists,pra:points+rebounds+assists,doubleCount:[points,rebounds,assists,blocks,steals].filter(value=>value>=10).length});}return rows;}
  function basketballThreshold(summary,leg){const target=Number(leg.target),teamMarket=clean(leg.type).startsWith('team_total');for(const play of basketballPlays(summary)){const away=Number(play?.awayScore),home=Number(play?.homeScore);if(!Number.isFinite(away)||!Number.isFinite(home))continue;const value=teamMarket?basketballScore(play,summary,leg.team):away+home;if(value!=null&&value>target)return{reached:true,time:basketballTime(play),value};}return{reached:false,time:'',value:null};}
  function basketballHeaderScores(summary){const competitors=basketballCompetitors(summary),away=Number(competitors.away.score),home=Number(competitors.home.score);return Number.isFinite(away)&&Number.isFinite(home)?{away,home}:null;}
  function basketballFinalValue(summary,leg){const last=basketballPlays(summary).at(-1);if(last){const value=clean(leg.type).startsWith('team_total')?basketballScore(last,summary,leg.team):Number(last.awayScore)+Number(last.homeScore);if(Number.isFinite(value))return value;}const scores=basketballHeaderScores(summary);if(!scores)return null;if(!clean(leg.type).startsWith('team_total'))return scores.away+scores.home;const side=basketballSide(summary,leg.team);return side==='away'?scores.away:side==='home'?scores.home:null;}
  function basketballFinalMatchup(summary,team){const last=basketballPlays(summary).at(-1);if(last){const mine=basketballScore(last,summary,team),opponent=basketballOpponent(last,summary,team);if(mine!=null&&opponent!=null)return{mine,opponent};}const scores=basketballHeaderScores(summary),side=basketballSide(summary,team);if(!scores||!side)return null;return side==='away'?{mine:scores.away,opponent:scores.home}:{mine:scores.home,opponent:scores.away};}
  function firstHalfSnapshot(summary){const plays=basketballPlays(summary),periodOf=play=>Number(play?.period?.number||play?.period||0),firstHalf=plays.filter(play=>periodOf(play)>0&&periodOf(play)<=2),complete=Boolean(firstHalf.length&&(plays.some(play=>periodOf(play)>=3)||Number(summary?.header?.competitions?.[0]?.status?.period||0)>=3||basketballFinal(summary)));if(!complete)return{complete:false,time:'',play:null};const play=firstHalf.at(-1);return{complete:true,time:basketballTime(play),play};}
  function settleBasketballLeg(leg,summary){
    const type=clean(leg.type),target=Number(leg.target),final=basketballFinal(summary),end=basketballFinalTime(summary);
    if(type==='void')return{status:'VOID',settledAt:end,reason:'Void finalized'};
    if(type==='manual')return{status:'PENDING',settledAt:'',reason:'Manual'};
    const key={player_points:'points',player_rebounds:'rebounds',player_assists:'assists',player_threes:'threes',player_blocks:'blocks',player_points_rebounds:'pr',player_pr:'pr',player_points_assists:'pa',player_pa:'pa',player_rebounds_assists:'ra',player_ra:'ra',player_points_rebounds_assists:'pra',player_pra:'pra',player_double_double:'doubleCount',player_triple_double:'doubleCount'}[type];
    if(key){const needed=type==='player_double_double'?2:type==='player_triple_double'?3:target,reached=threshold(basketballPlayerLedger(summary,leg.player),key,needed);if(reached.reached)return{status:'WIN',settledAt:reached.time,reason:`${key} target reached`};if(final){const value=basketballFinalPlayerValue(summary,leg,key);if(value==null||!Number.isFinite(value))return{status:'UNAVAILABLE',settledAt:'',reason:'Final player statistic unavailable'};return{status:value>=needed?'WIN':'LOSS',settledAt:end,reason:value>=needed?'Target confirmed by final box score':'Game final below target'};}return{status:'LIVE',settledAt:'',reason:''};}
    if(['team_total_over','total_over'].includes(type)){const reached=basketballThreshold(summary,leg);if(reached.reached)return{status:'WIN',settledAt:reached.time,reason:'Over threshold crossed'};if(final){const value=basketballFinalValue(summary,leg);return value==null?{status:'UNAVAILABLE',settledAt:'',reason:'Final score unavailable'}:{status:finalLineStatus(value,target,'over'),settledAt:end,reason:'Game final'};}return{status:'LIVE',settledAt:'',reason:''};}
    if(['team_total_under','total_under'].includes(type)){const loss=basketballThreshold(summary,leg);if(loss.reached)return{status:'LOSS',settledAt:loss.time,reason:'Under threshold crossed'};if(final){const value=basketballFinalValue(summary,leg);return value==null?{status:'UNAVAILABLE',settledAt:'',reason:'Final score unavailable'}:{status:finalLineStatus(value,target,'under'),settledAt:end,reason:'Game final'};}return{status:'LIVE',settledAt:'',reason:''};}
    if(['h1_ml','h1_spread','h1_total_over','h1_total_under'].includes(type)){const half=firstHalfSnapshot(summary);if(!half.complete)return{status:'LIVE',settledAt:'',reason:''};const away=Number(half.play?.awayScore),home=Number(half.play?.homeScore);if(!Number.isFinite(away)||!Number.isFinite(home))return{status:'UNAVAILABLE',settledAt:'',reason:'Halftime score unavailable'};if(type.startsWith('h1_total')){const direction=type.endsWith('_over')?'over':'under';return{status:finalLineStatus(away+home,target,direction),settledAt:half.time,reason:'First half complete'};}const mine=basketballScore(half.play,summary,leg.team),opponent=basketballOpponent(half.play,summary,leg.team);if(mine==null||opponent==null)return{status:'UNAVAILABLE',settledAt:'',reason:'Team unavailable'};const adjusted=type==='h1_spread'?mine+target:mine;return{status:adjusted>opponent?'WIN':adjusted<opponent?'LOSS':'VOID',settledAt:half.time,reason:'First half complete'};}
    if(['ml','spread'].includes(type)){if(!final)return{status:'LIVE',settledAt:'',reason:''};const scores=basketballFinalMatchup(summary,leg.team);if(!scores)return{status:'UNAVAILABLE',settledAt:'',reason:'Final score unavailable'};const adjusted=type==='spread'?scores.mine+target:scores.mine;return{status:adjusted>scores.opponent?'WIN':adjusted<scores.opponent?'LOSS':'VOID',settledAt:end,reason:'Game final'};}
    return{status:final?'UNAVAILABLE':'LIVE',settledAt:'',reason:'Unsupported basketball settlement mapping'};
  }

  function chooseTicketSettlement(results,outcome){const settled=results.filter(result=>result.settledAt);if(outcome==='LOST'){const losses=settled.filter(result=>result.status==='LOSS');return losses.reduce((best,item)=>!best||new Date(item.settledAt)<new Date(best.settledAt)?item:best,null);}if(outcome==='WON'){const wins=settled.filter(result=>result.status==='WIN');return wins.reduce((best,item)=>!best||new Date(item.settledAt)>new Date(best.settledAt)?item:best,null);}if(outcome==='PUSH'){const pushes=settled.filter(result=>result.status==='VOID');return pushes.reduce((best,item)=>!best||new Date(item.settledAt)>new Date(best.settledAt)?item:best,null);}return null;}
  async function resolve(record,outcome){const ticket=record.ticket||{},results=[];for(let index=0;index<(ticket.legs||[]).length;index++){const leg=ticket.legs[index],league=effectiveLeague(ticket,leg),game=leg.game||ticket.game,date=leg.date||ticket.date;if(!supportedLeague(league)||!game||!date){results.push({index,status:'UNAVAILABLE',settledAt:'',reason:'No supported event feed'});continue;}try{const result=league==='MLB'?settleMlbLeg(leg,await getMlbFeed(record,ticket,leg)):settleBasketballLeg(leg,await getBasketballSummary(record,ticket,leg,league));results.push({index,ledger:league==='MLB'?'mlb':'basketball',...result});}catch(error){results.push({index,status:'UNAVAILABLE',settledAt:'',reason:error?.message||'Feed unavailable'});}}return{results,ticketSettlement:chooseTicketSettlement(results,clean(outcome).toUpperCase())};}
  function compact(result){return{index:result.index,status:result.status,settledAt:result.settledAt||null,settlementReason:result.reason||''};}
  async function apply(record,outcome){
    const normalizedOutcome=clean(outcome).toUpperCase(),resolved=await resolve(record,normalizedOutcome),previous=new Map((record.legSettlements||[]).map(item=>[Number(item.index),item]));
    record.legSettlements=resolved.results.map(result=>{const prior=previous.get(Number(result.index));if(result.status==='UNAVAILABLE'&&prior&&['WIN','LOSS','VOID'].includes(prior.status))return prior;const next=compact(result);if(prior&&prior.status===next.status&&!next.settledAt&&prior.settledAt)next.settledAt=prior.settledAt;return next;});
    const settlement=resolved.ticketSettlement;
    if(settlement){record.settledAt=settlement.settledAt;record.settlementSource=settlement.ledger==='basketball'?'basketball-event-ledger':'mlb-event-ledger';record.settlementReason=settlement.reason||'';record.settlementLegIndexes=resolved.results.filter(result=>result.status===settlement.status&&result.settledAt===settlement.settledAt).map(result=>result.index);record.settledOutcome=normalizedOutcome;record.settlementPending=false;}
    else if(record.settledOutcome!==normalizedOutcome){delete record.settledAt;delete record.settlementSource;delete record.settlementReason;delete record.settlementLegIndexes;delete record.settledOutcome;record.settlementPending=['WON','LOST','PUSH'].includes(normalizedOutcome);}
    return record;
  }
  function reset(){cache.clear();}
  window.ParlaySettlementService=Object.freeze({apply,resolve,reset,supportedLeague,supports});
})();
